os:
  - linux
sudo: false
addons:
  apt:
    packages:
    - libstdc++6
    - lib32stdc++6
script:
  - git clone https://github.com/flutter/flutter.git -b beta ../flutter -b beta --depth 1
  - ../flutter/bin/flutter doctor
  - ../flutter/bin/flutter analyze
cache:
  directories:
  - $HOME/.pub-cache
