name: month_picker_dialog
description: Internationalized dialog for picking a single month from an infinite list of years.
version: 0.6.3
homepage: https://github.com/hmkrivoj/month_picker_dialog

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.27.7
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
flutter:
