name: month_picker_dialog
description: Internationalized dialog for picking a single month from an infinite list of years.
version: 6.7.2
homepage: https://github.com/Macacoazul01/month_picker_dialog

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  intl: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
